// require("prismjs/themes/prism-tomorrow.css")
require(`prismjs/prism.js`)
require(`prismjs/components/prism-clike.js`)
require(`prismjs/components/prism-c.js`)
require(`prismjs/components/prism-cpp.js`)
require(`prismjs/components/prism-git.js`)