import React from 'react'
import { Link, graphql } from 'gatsby'
import { Helmet } from 'react-helmet'
import { IndexPageQuery, IndexPageQueryVariables } from 'generated/types/gatsby'
// import { ContentList } from '../components/ContentList'
// import { Pager } from '../components/Pager'
// import { Layout } from '../components/Layout'
// import { ArchivePageContext } from '../context'